"""Durable PostgreSQL storage for the course catalog and selection history."""

from __future__ import annotations

import hashlib
import json
import threading
from datetime import datetime, timedelta
from pathlib import Path

from psycopg2.extras import Json

from backend.storage.postgres import postgres_connection


_INIT_LOCK = threading.RLock()
_INITIALIZED = False


def course_db():
    return postgres_connection()


def _json_file(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except Exception:
        return {}


def _timestamp(value):
    return value or None


def _fallback_course_key(url: str) -> str:
    return hashlib.sha1(str(url or "").encode("utf-8")).hexdigest()[:16]


def _create_schema(connection) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS course_catalog (
                course_key TEXT PRIMARY KEY,
                canonical_url TEXT NOT NULL,
                title TEXT NOT NULL DEFAULT '',
                platform TEXT NOT NULL DEFAULT '',
                level TEXT NOT NULL DEFAULT '',
                payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                first_seen_at TIMESTAMPTZ,
                last_verified_at TIMESTAMPTZ,
                selected_count INTEGER NOT NULL DEFAULT 0,
                last_selected_at TIMESTAMPTZ,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_catalog_url ON course_catalog (canonical_url)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_catalog_level ON course_catalog (level)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_catalog_platform ON course_catalog (platform)")
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS course_selection_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                issue_id TEXT NOT NULL,
                issue_date TIMESTAMPTZ NOT NULL,
                course_key TEXT NOT NULL,
                canonical_url TEXT NOT NULL,
                platform TEXT NOT NULL DEFAULT '',
                level TEXT NOT NULL DEFAULT '',
                selected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (issue_id, canonical_url)
            )
            """
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_selections_date ON course_selection_events (issue_date DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_selections_url ON course_selection_events (canonical_url)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_course_selections_platform ON course_selection_events (platform)")
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS course_rotation_state (
                state_key TEXT PRIMARY KEY,
                state JSONB NOT NULL DEFAULT '{}'::jsonb,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS course_storage_meta (
                meta_key TEXT PRIMARY KEY,
                value JSONB NOT NULL DEFAULT '{}'::jsonb,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


def _upsert_courses(connection, courses: list[dict]) -> dict:
    rows = [item for item in courses if isinstance(item, dict) and item.get("course_key") and item.get("url")]
    keys = [str(item["course_key"]) for item in rows]
    existing = set()
    if keys:
        with connection.cursor() as cursor:
            cursor.execute("SELECT course_key FROM course_catalog WHERE course_key = ANY(%s)", (keys,))
            existing = {row[0] for row in cursor.fetchall()}
    with connection.cursor() as cursor:
        for item in rows:
            cursor.execute(
                """
                INSERT INTO course_catalog (
                    course_key, canonical_url, title, platform, level, payload,
                    first_seen_at, last_verified_at, selected_count, last_selected_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (course_key) DO UPDATE SET
                    canonical_url = EXCLUDED.canonical_url,
                    title = EXCLUDED.title,
                    platform = EXCLUDED.platform,
                    level = EXCLUDED.level,
                    payload = EXCLUDED.payload,
                    first_seen_at = COALESCE(course_catalog.first_seen_at, EXCLUDED.first_seen_at),
                    last_verified_at = COALESCE(EXCLUDED.last_verified_at, course_catalog.last_verified_at),
                    selected_count = GREATEST(course_catalog.selected_count, EXCLUDED.selected_count),
                    last_selected_at = COALESCE(course_catalog.last_selected_at, EXCLUDED.last_selected_at),
                    updated_at = CURRENT_TIMESTAMP
                """,
                (
                    str(item.get("course_key") or ""),
                    str(item.get("url") or ""),
                    str(item.get("title") or ""),
                    str(item.get("platform") or ""),
                    str(item.get("level") or ""),
                    Json(item),
                    _timestamp(item.get("first_seen_at")),
                    _timestamp(item.get("last_verified_at")),
                    int(item.get("selected_count") or 0),
                    _timestamp(item.get("last_selected_at")),
                ),
            )
    return {"added": len(set(keys) - existing), "updated": len(set(keys) & existing), "total": 0}


def _migrate_legacy(connection, bank_path: Path, history_path: Path) -> None:
    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM course_storage_meta WHERE meta_key = 'legacy_json_migrated'")
        if cursor.fetchone():
            return

    bank = _json_file(bank_path)
    history = _json_file(history_path)
    courses = list((bank.get("courses") or {}).values())
    _upsert_courses(connection, courses)

    with connection.cursor() as cursor:
        cursor.execute("SELECT canonical_url, course_key FROM course_catalog")
        keys_by_url = {row[0]: row[1] for row in cursor.fetchall()}
        for row in history.get("selections") or []:
            url = str(row.get("course_url") or "")
            if not url or not row.get("issue_id") or not row.get("issue_date"):
                continue
            cursor.execute(
                """
                INSERT INTO course_selection_events (
                    issue_id, issue_date, course_key, canonical_url, platform, level
                ) VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (issue_id, canonical_url) DO NOTHING
                """,
                (
                    str(row.get("issue_id") or ""),
                    row.get("issue_date"),
                    keys_by_url.get(url) or _fallback_course_key(url),
                    url,
                    str(row.get("platform") or ""),
                    str(row.get("level") or ""),
                ),
            )
        rotation = history.get("platform_rotation")
        if isinstance(rotation, dict) and rotation:
            cursor.execute(
                """
                INSERT INTO course_rotation_state (state_key, state)
                VALUES ('weekly', %s)
                ON CONFLICT (state_key) DO UPDATE SET state = EXCLUDED.state, updated_at = CURRENT_TIMESTAMP
                """,
                (Json(rotation),),
            )
        cursor.execute(
            """
            INSERT INTO course_storage_meta (meta_key, value)
            VALUES ('legacy_json_migrated', %s)
            ON CONFLICT (meta_key) DO UPDATE SET value = EXCLUDED.value, updated_at = CURRENT_TIMESTAMP
            """,
            (Json({"courses": len(courses), "selections": len(history.get("selections") or [])}),),
        )


def ensure_course_storage(bank_path: Path, history_path: Path) -> None:
    global _INITIALIZED
    if _INITIALIZED:
        return
    with _INIT_LOCK:
        if _INITIALIZED:
            return
        connection = course_db()
        try:
            _create_schema(connection)
            _migrate_legacy(connection, bank_path, history_path)
            connection.commit()
            _INITIALIZED = True
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()


def upsert_courses(courses: list[dict]) -> dict:
    connection = course_db()
    try:
        stats = _upsert_courses(connection, courses)
        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM course_catalog")
            stats["total"] = int(cursor.fetchone()[0])
        connection.commit()
        return stats
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def load_courses() -> list[dict]:
    connection = course_db()
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT payload, course_key, canonical_url, selected_count, last_selected_at,
                       first_seen_at, last_verified_at
                FROM course_catalog
                ORDER BY updated_at DESC, course_key
                """
            )
            output = []
            for payload, key, url, selected_count, last_selected_at, first_seen_at, last_verified_at in cursor.fetchall():
                item = dict(payload or {})
                item["course_key"] = key
                item["url"] = url
                item["selected_count"] = int(selected_count or 0)
                if last_selected_at:
                    item["last_selected_at"] = last_selected_at.isoformat()
                if first_seen_at:
                    item["first_seen_at"] = first_seen_at.isoformat()
                if last_verified_at:
                    item["last_verified_at"] = last_verified_at.isoformat()
                output.append(item)
            return output
    finally:
        connection.close()


def selection_context(issue_id: str, issue_date: datetime, repeat_days: int) -> tuple[set[str], set[str], dict]:
    cutoff = issue_date - timedelta(days=repeat_days)
    connection = course_db()
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT DISTINCT canonical_url
                FROM course_selection_events
                WHERE issue_id <> %s AND issue_date >= %s
                """,
                (issue_id, cutoff),
            )
            repeated_urls = {row[0] for row in cursor.fetchall() if row[0]}
            cursor.execute(
                """
                SELECT MAX(issue_date)
                FROM course_selection_events
                WHERE issue_id <> %s AND issue_date < %s
                """,
                (issue_id, issue_date),
            )
            previous_date = cursor.fetchone()[0]
            previous_platforms = set()
            if previous_date:
                cursor.execute(
                    "SELECT DISTINCT platform FROM course_selection_events WHERE issue_date = %s",
                    (previous_date,),
                )
                previous_platforms = {str(row[0] or "").strip().lower() for row in cursor.fetchall() if row[0]}
            cursor.execute("SELECT state FROM course_rotation_state WHERE state_key = 'weekly'")
            row = cursor.fetchone()
            rotation = dict(row[0] or {}) if row else {}
        return repeated_urls, previous_platforms, rotation
    finally:
        connection.close()


def record_selection(issue_id: str, issue_date: datetime, selected: list[dict], rotation: dict) -> None:
    connection = course_db()
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT course_key FROM course_selection_events WHERE issue_id = %s", (issue_id,))
            previous_keys = {row[0] for row in cursor.fetchall()}
            selected_keys = {
                str(item.get("course_key") or _fallback_course_key(item.get("url") or ""))
                for item in selected
                if item.get("url")
            }
            cursor.execute("DELETE FROM course_selection_events WHERE issue_id = %s", (issue_id,))
            for item in selected:
                key = str(item.get("course_key") or _fallback_course_key(item.get("url") or ""))
                cursor.execute(
                    """
                    INSERT INTO course_selection_events (
                        issue_id, issue_date, course_key, canonical_url, platform, level
                    ) VALUES (%s, %s, %s, %s, %s, %s)
                    ON CONFLICT (issue_id, canonical_url) DO NOTHING
                    """,
                    (
                        issue_id,
                        issue_date,
                        key,
                        str(item.get("url") or ""),
                        str(item.get("platform") or ""),
                        str(item.get("level") or ""),
                    ),
                )
            cursor.execute(
                """
                INSERT INTO course_rotation_state (state_key, state)
                VALUES ('weekly', %s)
                ON CONFLICT (state_key) DO UPDATE SET state = EXCLUDED.state, updated_at = CURRENT_TIMESTAMP
                """,
                (Json(rotation),),
            )
            for key in previous_keys - selected_keys:
                cursor.execute(
                    """
                    UPDATE course_catalog
                    SET selected_count = GREATEST(0, selected_count - 1),
                        updated_at = CURRENT_TIMESTAMP
                    WHERE course_key = %s
                    """,
                    (key,),
                )
            for key in selected_keys - previous_keys:
                cursor.execute(
                    """
                    UPDATE course_catalog
                    SET selected_count = selected_count + 1,
                        last_selected_at = GREATEST(COALESCE(last_selected_at, %s), %s),
                        updated_at = CURRENT_TIMESTAMP
                    WHERE course_key = %s
                    """,
                    (issue_date, issue_date, key),
                )
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()
