# This file is part of the AI newsletter system.
"""One-time, idempotent migration of newsletter versions to PostgreSQL."""

from __future__ import annotations

import os
import sqlite3
from collections import Counter
from pathlib import Path

from dotenv import load_dotenv

from backend.storage.postgres import postgres_connection


# Migration step 1: load the same local environment file used by the backend,
# while allowing Docker-provided PostgreSQL settings to remain authoritative.
BACKEND_DIR = Path(__file__).resolve().parents[1]
PROJECT_DIR = BACKEND_DIR.parent
load_dotenv(BACKEND_DIR / ".env", override=False)


# Migration step 2: keep the legacy SQLite source read-only and configurable,
# defaulting to the 11-record database retained under data/versions/.
SQLITE_VERSIONS_PATH = Path(
    os.getenv("SQLITE_VERSIONS_PATH", str(PROJECT_DIR / "data" / "versions" / "versions.db"))
)


# Migration step 4: read every legacy row without modifying the SQLite backup.
def read_legacy_versions() -> list[tuple]:
    if not SQLITE_VERSIONS_PATH.exists():
        raise FileNotFoundError(f"Legacy SQLite database not found: {SQLITE_VERSIONS_PATH}")
    uri = SQLITE_VERSIONS_PATH.resolve().as_uri() + "?mode=ro"
    con = sqlite3.connect(uri, uri=True)
    try:
        return con.execute(
            """
            SELECT id, issue_number, title, created_at, content, kind, pdf_path, original_filename
            FROM versions
            ORDER BY id
            """
        ).fetchall()
    finally:
        con.close()


# Migration step 5: create the PostgreSQL table when the application has not
# started yet, using the same schema as server_versions.py.
def ensure_postgres_schema(con) -> None:
    with con.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS versions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                issue_number INTEGER,
                title TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                content TEXT,
                kind TEXT DEFAULT 'json',
                -- PDF BYTEA change: pdf_path is deprecated after legacy files
                -- are copied into the PostgreSQL binary column.
                pdf_path TEXT,
                original_filename TEXT,
                pdf_data BYTEA
            )
            """
        )
        # PDF BYTEA change: keep this Step 1 migration compatible with databases
        # created before the binary PDF column was introduced.
        cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS pdf_data BYTEA")


# Migration step 6: insert explicit legacy IDs and skip conflicts so rerunning
# the script never duplicates versions that were already migrated.
def migrate_rows(con, rows: list[tuple]) -> Counter:
    inserted = Counter()
    with con.cursor() as cur:
        for row in rows:
            cur.execute(
                """
                INSERT INTO versions (
                    id, issue_number, title, created_at, content, kind, pdf_path, original_filename
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
                RETURNING kind
                """,
                row,
            )
            result = cur.fetchone()
            if result:
                inserted[(result[0] or "json").lower()] += 1

        # Migration step 7: advance the PostgreSQL identity sequence beyond the
        # highest migrated ID so future API inserts cannot collide.
        cur.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('versions', 'id'),
                COALESCE((SELECT MAX(id) FROM versions), 1),
                EXISTS(SELECT 1 FROM versions)
            )
            """
        )
    return inserted


# Migration step 8: report source, inserted, skipped, and final PostgreSQL totals
# with separate JSON and PDF counts for an auditable one-time migration.
def main() -> None:
    rows = read_legacy_versions()
    source = Counter((row[5] or "json").lower() for row in rows)
    con = postgres_connection()
    try:
        ensure_postgres_schema(con)
        inserted = migrate_rows(con, rows)
        con.commit()
        with con.cursor() as cur:
            cur.execute("SELECT COALESCE(kind, 'json'), COUNT(*) FROM versions GROUP BY COALESCE(kind, 'json')")
            final = Counter({kind.lower(): count for kind, count in cur.fetchall()})
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()

    skipped = Counter({kind: source[kind] - inserted[kind] for kind in source})
    print(f"SQLite source: {SQLITE_VERSIONS_PATH}")
    print(f"Source records: total={len(rows)} json={source['json']} pdf={source['pdf']}")
    print(f"Inserted this run: total={sum(inserted.values())} json={inserted['json']} pdf={inserted['pdf']}")
    print(f"Already present: total={sum(skipped.values())} json={skipped['json']} pdf={skipped['pdf']}")
    print(f"PostgreSQL totals: total={sum(final.values())} json={final['json']} pdf={final['pdf']}")


# Migration step 9: run only when invoked directly, never during backend import.
if __name__ == "__main__":
    main()

