# This file is part of the AI newsletter system.
"""PostgreSQL schema setup, legacy SQLite migration/seeding, and small
version-metadata helpers (titles, filenames, datetime formatting) shared by
the PDF import pipeline and the HTTP route handlers.
"""

from __future__ import annotations

import datetime
import json
import re
from pathlib import Path

import psycopg2

from backend.storage.postgres import postgres_connection
from backend.utils.debug_logging import trace
from backend.storage.newsletter_store import (
    NEWS_JSON_FILE,
    canonical_newsletter_payload,
    load_newsletter_settings,
    newsletter_template_from_settings,
    safe_int,
)

API_BASE = "/api"
SEED_VERSIONS_DB_FILE = Path(__file__).resolve().parent / "seeds" / "initial_versions.db"
_JSON_VERSIONS_CANONICALIZED = False
_VERSION_TITLE_UNIQUENESS_ENFORCED = False


def init_versions_db():
    con = versions_db()
    try:
        with con.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS versions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    issue_number INTEGER,
                    title TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    content TEXT,
                    kind TEXT DEFAULT 'json',
                    -- PDF BYTEA change: pdf_path is deprecated and remains only
                    -- long enough to migrate legacy files into pdf_data.
                    pdf_path TEXT,
                    original_filename TEXT,
                    pdf_data BYTEA,
                    hidden_from_users BOOLEAN DEFAULT FALSE
                )
            """)
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS kind TEXT DEFAULT 'json'")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS pdf_path TEXT")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS original_filename TEXT")
            # PDF BYTEA change: add binary storage without changing existing JSON rows.
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS pdf_data BYTEA")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS hidden_from_users BOOLEAN DEFAULT FALSE")
        con.commit()
    finally:
        con.close()
    seed_versions_from_sqlite_if_empty()
    migrate_json_versions_to_canonical_schema()
    enforce_unique_version_titles()


def migrate_json_versions_to_canonical_schema():
    """One-time runtime migration for old/manual JSON version snapshots."""
    global _JSON_VERSIONS_CANONICALIZED
    if _JSON_VERSIONS_CANONICALIZED:
        return
    con = versions_db()
    migrated = 0
    try:
        with con.cursor() as cur:
            cur.execute(
                "SELECT id, title, content FROM versions "
                "WHERE COALESCE(kind, 'json') = 'json'"
            )
            rows = cur.fetchall()
        with con.cursor() as cur:
            for version_id, current_title, content in rows:
                try:
                    raw = json.loads(content or "{}")
                    canonical = canonical_newsletter_payload(raw)
                except Exception as exc:
                    trace(f"Version {version_id} canonical migration skipped: {exc}")
                    continue
                canonical_text = json.dumps(canonical, ensure_ascii=False, indent=2)
                metadata = canonical.get("metadata") if isinstance(canonical.get("metadata"), dict) else {}
                requested_title = str(metadata.get("requested_version_title") or "").strip()
                next_title = requested_title or str(current_title or "").strip()
                if canonical_text != str(content or "") or next_title != str(current_title or "").strip():
                    cur.execute(
                        "UPDATE versions SET title = %s, content = %s WHERE id = %s",
                        (next_title, canonical_text, version_id),
                    )
                    migrated += 1
        con.commit()
        _JSON_VERSIONS_CANONICALIZED = True
        if migrated:
            trace(f"Canonicalized {migrated} stored JSON newsletter versions")
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()


# seeds/initial_versions.db ships with the historical starter versions, but a
# genuinely fresh PostgreSQL volume (first-time clone/
# setup, or a collaborator's machine) starts with an empty versions table -
# init_versions_db() only does CREATE TABLE IF NOT EXISTS, it never
# populates data. Without this, "previous versions" is silently empty on
# every fresh environment even though the repo has the history. Runs once:
# after the first successful seed the table is non-empty, so every later
# call is just a cheap COUNT(*) short-circuit.
SEED_VERSIONS_DB_FILE = Path(__file__).resolve().parent / "seeds" / "initial_versions.db"


def seed_versions_from_sqlite_if_empty():
    if not SEED_VERSIONS_DB_FILE.exists():
        return
    con = versions_db()
    try:
        with con.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM versions")
            (count,) = cur.fetchone()
        if count:
            return
        import sqlite3
        sconn = sqlite3.connect(str(SEED_VERSIONS_DB_FILE))
        try:
            rows = sconn.execute(
                "SELECT id, issue_number, title, created_at, content, kind, "
                "pdf_path, original_filename, pdf_data, hidden_from_users "
                "FROM versions ORDER BY id"
            ).fetchall()
        finally:
            sconn.close()
        if not rows:
            return
        with con.cursor() as cur:
            for row in rows:
                (vid, issue_number, title, created_at, content, kind,
                 pdf_path, original_filename, pdf_data, hidden) = row
                cur.execute(
                    """
                    INSERT INTO versions (id, issue_number, title, created_at, content,
                                           kind, pdf_path, original_filename, pdf_data, hidden_from_users)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    (
                        vid, issue_number, title, created_at, content, kind,
                        pdf_path, original_filename,
                        psycopg2.Binary(pdf_data) if pdf_data is not None else None,
                        bool(hidden),
                    ),
                )
            # Explicit ids bypass the identity sequence - advance it past the
            # seeded max so the next user-saved version doesn't collide.
            cur.execute(
                "SELECT setval(pg_get_serial_sequence('versions', 'id'), "
                "COALESCE((SELECT MAX(id) FROM versions), 1))"
            )
        con.commit()
        trace(f"Seeded {len(rows)} versions from {SEED_VERSIONS_DB_FILE} into empty PostgreSQL table")
    except Exception as exc:
        con.rollback()
        trace(f"Version seed from SQLite failed: {exc}")
    finally:
        con.close()


# PostgreSQL change: centralize psycopg2 connection creation for every existing
# version endpoint while keeping the calling functions and routes unchanged.
def versions_db():
    return postgres_connection()


# BACKUP NOTE: There is no automated backup of the PostgreSQL versions data.
# A previous backup_versions_db() function was called after every important
# change but never actually copied or saved anything - it was a no-op that
# made backups look like they existed when they didn't, so it was removed
# rather than kept as misleading dead code. A real backup (e.g. periodic
# pg_dump, with a retention policy and a tested restore path) is a separate,
# still-unscoped task - don't reintroduce a call here without one.


# PostgreSQL change: normalize psycopg2 datetime objects to the string format
# previously returned by SQLite so API response shapes remain stable.
def serialize_db_datetime(value):
    if isinstance(value, (datetime.datetime, datetime.date)):
        return value.isoformat(sep=" ")
    return value


# PDF BYTEA change: preserve the existing helper name but store PDF bytes in
# PostgreSQL instead of writing a local file. pdf_path is explicitly cleared
# because it is deprecated after the legacy-file migration.
def save_pdf_version_file(version_id: int, pdf_bytes: bytes, filename: str = "", connection=None) -> int:
    owns_connection = connection is None
    con = connection or versions_db()
    try:
        with con.cursor() as cur:
            cur.execute(
                "UPDATE versions SET pdf_data = %s, pdf_path = NULL WHERE id = %s",
                (psycopg2.Binary(pdf_bytes or b""), version_id),
            )
            updated = cur.rowcount
        if owns_connection:
            con.commit()
        return updated
    except Exception:
        if owns_connection:
            con.rollback()
        raise
    finally:
        if owns_connection:
            con.close()


# Performs the title from pdf filename helper step.
def title_from_pdf_filename(filename: str = "") -> str:
    stem = Path(str(filename or "")).stem.strip()
    return stem or "PDF مستورد"


# Performs the parse version id helper step.
def parse_version_id(path, suffix=""):
    prefix = f"{API_BASE}/versions/"
    if not path.startswith(prefix):
        return None
    tail = path[len(prefix):]
    if suffix:
        if not tail.endswith(suffix):
            return None
        tail = tail[:-len(suffix)]
    if "/" in tail or not tail:
        return None
    try:
        return int(tail)
    except ValueError:
        return None


# Reads load current news json text from the current store or request context.
def load_current_news_json_text():
    if not NEWS_JSON_FILE.exists():
        return ""
    raw_text = NEWS_JSON_FILE.read_text(encoding="utf-8")
    try:
        raw = json.loads(raw_text)
    except Exception:
        return raw_text
    return json.dumps(canonical_newsletter_payload(raw), ensure_ascii=False, indent=2)


def requested_version_title_from_news(content_text):
    try:
        payload = json.loads(content_text)
    except Exception:
        return ""
    metadata = payload.get("metadata") if isinstance(payload, dict) else {}
    if not isinstance(metadata, dict):
        return ""
    return str(metadata.get("requested_version_title") or "").strip()


# Performs the version title from news helper step.
def version_title_from_news(content_text):
    try:
        payload = json.loads(content_text)
    except Exception:
        payload = {}
    template = payload.get("template") if isinstance(payload.get("template"), dict) else {}
    settings = load_newsletter_settings()
    issue_number = safe_int(
        template.get("issue_number") or settings.get("issue_number"),
        settings.get("issue_number") or 1,
    )
    month_year = str(
        template.get("month_year")
        or template.get("month_year_override")
        or settings.get("month_year_override")
        or ""
    ).strip()
    if not month_year:
        month_year = newsletter_template_from_settings(settings).get("month_year", "")
    title = f"نشرة الذكاء الاصطناعي الإصدار {issue_number} — {month_year}".strip()
    return issue_number, title


def normalize_version_title(value: str) -> str:
    """Normalize visible whitespace without changing the user's title."""
    return re.sub(r"\s+", " ", str(value or "")).strip()


def version_title_exists(connection, requested_title: str, exclude_id: int | None = None) -> bool:
    """Return whether another saved version already uses this title."""
    title = normalize_version_title(requested_title)
    if not title:
        return False
    query = "SELECT 1 FROM versions WHERE LOWER(BTRIM(title)) = LOWER(BTRIM(%s))"
    values: list[object] = [title]
    if exclude_id is not None:
        query += " AND id <> %s"
        values.append(int(exclude_id))
    query += " LIMIT 1"
    with connection.cursor() as cur:
        cur.execute(query, tuple(values))
        return cur.fetchone() is not None


def enforce_unique_version_titles() -> None:
    """Deduplicate legacy titles once, then enforce uniqueness in PostgreSQL."""
    global _VERSION_TITLE_UNIQUENESS_ENFORCED
    if _VERSION_TITLE_UNIQUENESS_ENFORCED:
        return
    con = versions_db()
    try:
        with con.cursor() as cur:
            cur.execute(
                "SELECT id, title FROM versions "
                "WHERE BTRIM(COALESCE(title, '')) <> '' ORDER BY id"
            )
            rows = cur.fetchall()

        updates = legacy_unique_title_updates(rows)

        with con.cursor() as cur:
            if updates:
                cur.executemany(
                    "UPDATE versions SET title = %s WHERE id = %s",
                    updates,
                )
            cur.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS versions_title_unique_ci
                ON versions ((LOWER(BTRIM(title))))
                WHERE BTRIM(COALESCE(title, '')) <> ''
                """
            )
        con.commit()
        _VERSION_TITLE_UNIQUENESS_ENFORCED = True
        if updates:
            trace(f"Renamed {len(updates)} legacy duplicate version title(s)")
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()


def legacy_unique_title_updates(rows) -> list[tuple[str, int]]:
    """Return deterministic rename operations for duplicate historical rows."""
    used: set[str] = set()
    updates: list[tuple[str, int]] = []
    for version_id, raw_title in rows:
        base = normalize_version_title(raw_title)
        candidate = base
        suffix = 2
        while candidate.casefold() in used:
            candidate = f"{base} ({suffix})"
            suffix += 1
        used.add(candidate.casefold())
        if candidate != str(raw_title or ""):
            updates.append((candidate, int(version_id)))
    return updates
