# This file is part of the AI newsletter system.
"""Version management routes and PDF import helpers for the HTTP server."""

from __future__ import annotations

import base64
import datetime
import hashlib
import html
import io
import json
import os
import re
import unicodedata
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from email.parser import BytesParser
from email.policy import default as email_default_policy
from pathlib import Path

import psycopg2
from dotenv import load_dotenv

from backend.utils.debug_logging import trace
from backend.storage.newsletter_store import (
    DISPLAY_COUNTS,
    NEWS_JSON_FILE,
    publish_current_store,
    load_newsletter_settings,
    newsletter_template_from_settings,
    safe_int,
)

ROOT_DIR = Path(__file__).resolve().parents[1]
API_BASE = "/api"

load_dotenv(ROOT_DIR / ".env", override=True)


# Performs the env path helper step.
def env_path(name: str, default: Path) -> Path:
    value = os.getenv(name, "").strip()
    return Path(value) if value else default


# PostgreSQL change: version records now use the PostgreSQL service instead of
# opening backend/versions.db. The legacy SQLite path remains untouched on disk.
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost").strip() or "localhost"
POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", "5432") or "5432")
POSTGRES_DB = os.getenv("POSTGRES_DB", "ainewsletter").strip() or "ainewsletter"
POSTGRES_USER = os.getenv("POSTGRES_USER", "ainewsletter").strip() or "ainewsletter"
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "ainewsletter_local")

VERSIONS_BACKUP_DIR = env_path("VERSIONS_BACKUP_DIR", ROOT_DIR / "backups")
PDF_IMPORT_DEBUG_DIR = env_path("PDF_IMPORT_DEBUG_DIR", ROOT_DIR / "logs")
# PDF BYTEA change: this directory is retained only for the one-time legacy
# migration. Runtime imports no longer write files here.
PDF_VERSION_FILES_DIR = env_path("PDF_VERSION_FILES_DIR", ROOT_DIR / "pdf_versions")


# PostgreSQL change: create the same versions schema with an identity column so
# existing API behavior and migrated IDs remain compatible.
def init_versions_db():
    con = versions_db()
    try:
        with con.cursor() as cur:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS versions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    issue_number INTEGER,
                    title TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    content TEXT,
                    kind TEXT DEFAULT 'json',
                    -- PDF BYTEA change: pdf_path is deprecated and remains only
                    -- long enough to migrate legacy files into pdf_data.
                    pdf_path TEXT,
                    original_filename TEXT,
                    pdf_data BYTEA,
                    hidden_from_users BOOLEAN DEFAULT FALSE
                )
            """)
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS kind TEXT DEFAULT 'json'")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS pdf_path TEXT")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS original_filename TEXT")
            # PDF BYTEA change: add binary storage without changing existing JSON rows.
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS pdf_data BYTEA")
            cur.execute("ALTER TABLE versions ADD COLUMN IF NOT EXISTS hidden_from_users BOOLEAN DEFAULT FALSE")
        con.commit()
    finally:
        con.close()
    seed_versions_from_sqlite_if_empty()


# backend/versions.db ships in the repo with real version history (see
# UPDATES.md), but a genuinely fresh PostgreSQL volume (first-time clone/
# setup, or a collaborator's machine) starts with an empty versions table -
# init_versions_db() only does CREATE TABLE IF NOT EXISTS, it never
# populates data. Without this, "previous versions" is silently empty on
# every fresh environment even though the repo has the history. Runs once:
# after the first successful seed the table is non-empty, so every later
# call is just a cheap COUNT(*) short-circuit.
SEED_VERSIONS_DB_FILE = Path(__file__).resolve().parents[2] / "versions.db"


def seed_versions_from_sqlite_if_empty():
    if not SEED_VERSIONS_DB_FILE.exists():
        return
    con = versions_db()
    try:
        with con.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM versions")
            (count,) = cur.fetchone()
        if count:
            return
        import sqlite3
        sconn = sqlite3.connect(str(SEED_VERSIONS_DB_FILE))
        try:
            rows = sconn.execute(
                "SELECT id, issue_number, title, created_at, content, kind, "
                "pdf_path, original_filename, pdf_data, hidden_from_users "
                "FROM versions ORDER BY id"
            ).fetchall()
        finally:
            sconn.close()
        if not rows:
            return
        with con.cursor() as cur:
            for row in rows:
                (vid, issue_number, title, created_at, content, kind,
                 pdf_path, original_filename, pdf_data, hidden) = row
                cur.execute(
                    """
                    INSERT INTO versions (id, issue_number, title, created_at, content,
                                           kind, pdf_path, original_filename, pdf_data, hidden_from_users)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (id) DO NOTHING
                    """,
                    (
                        vid, issue_number, title, created_at, content, kind,
                        pdf_path, original_filename,
                        psycopg2.Binary(pdf_data) if pdf_data is not None else None,
                        bool(hidden),
                    ),
                )
            # Explicit ids bypass the identity sequence - advance it past the
            # seeded max so the next user-saved version doesn't collide.
            cur.execute(
                "SELECT setval(pg_get_serial_sequence('versions', 'id'), "
                "COALESCE((SELECT MAX(id) FROM versions), 1))"
            )
        con.commit()
        trace(f"Seeded {len(rows)} versions from {SEED_VERSIONS_DB_FILE} into empty PostgreSQL table")
    except Exception as exc:
        con.rollback()
        trace(f"Version seed from SQLite failed: {exc}")
    finally:
        con.close()


# PostgreSQL change: centralize psycopg2 connection creation for every existing
# version endpoint while keeping the calling functions and routes unchanged.
def versions_db():
    return psycopg2.connect(
        host=POSTGRES_HOST,
        port=POSTGRES_PORT,
        dbname=POSTGRES_DB,
        user=POSTGRES_USER,
        password=POSTGRES_PASSWORD,
        connect_timeout=5,
    )


# PostgreSQL change: per-operation SQLite file copies are intentionally disabled.
# The existing SQLite file remains the final legacy backup; PostgreSQL backups
# will be implemented with pg_dump in a future migration step.
def backup_versions_db():
    return None


# PostgreSQL change: normalize psycopg2 datetime objects to the string format
# previously returned by SQLite so API response shapes remain stable.
def serialize_db_datetime(value):
    if isinstance(value, (datetime.datetime, datetime.date)):
        return value.isoformat(sep=" ")
    return value


# Performs the safe pdf filename helper step.
def safe_pdf_filename(version_id: int, filename: str = "") -> str:
    stem = Path(str(filename or "imported.pdf")).stem.strip() or "imported"
    stem = re.sub(r"[^\w\u0600-\u06FF.-]+", "_", stem, flags=re.UNICODE).strip("._") or "imported"
    return f"version_{int(version_id)}_{stem}.pdf"


# PDF BYTEA change: preserve the existing helper name but store PDF bytes in
# PostgreSQL instead of writing a local file. pdf_path is explicitly cleared
# because it is deprecated after the legacy-file migration.
def save_pdf_version_file(version_id: int, pdf_bytes: bytes, filename: str = "", connection=None) -> int:
    owns_connection = connection is None
    con = connection or versions_db()
    try:
        with con.cursor() as cur:
            cur.execute(
                "UPDATE versions SET pdf_data = %s, pdf_path = NULL WHERE id = %s",
                (psycopg2.Binary(pdf_bytes or b""), version_id),
            )
            updated = cur.rowcount
        if owns_connection:
            con.commit()
        return updated
    except Exception:
        if owns_connection:
            con.rollback()
        raise
    finally:
        if owns_connection:
            con.close()


# Performs the title from pdf filename helper step.
def title_from_pdf_filename(filename: str = "") -> str:
    stem = Path(str(filename or "")).stem.strip()
    return stem or "PDF مستورد"


# Performs the parse version id helper step.
def parse_version_id(path, suffix=""):
    prefix = f"{API_BASE}/versions/"
    if not path.startswith(prefix):
        return None
    tail = path[len(prefix):]
    if suffix:
        if not tail.endswith(suffix):
            return None
        tail = tail[:-len(suffix)]
    if "/" in tail or not tail:
        return None
    try:
        return int(tail)
    except ValueError:
        return None


# Reads load current news json text from the current store or request context.
def load_current_news_json_text():
    if not NEWS_JSON_FILE.exists():
        return ""
    return NEWS_JSON_FILE.read_text(encoding="utf-8")


# Performs the version title from news helper step.
def version_title_from_news(content_text):
    try:
        payload = json.loads(content_text)
    except Exception:
        payload = {}
    template = payload.get("template") if isinstance(payload.get("template"), dict) else {}
    settings = load_newsletter_settings()
    issue_number = safe_int(
        template.get("issue_number") or settings.get("issue_number"),
        settings.get("issue_number") or 1,
    )
    month_year = str(
        template.get("month_year")
        or template.get("month_year_override")
        or settings.get("month_year_override")
        or ""
    ).strip()
    if not month_year:
        month_year = newsletter_template_from_settings(settings).get("month_year", "")
    title = f"نشرة الذكاء الاصطناعي الإصدار {issue_number} — {month_year}".strip()
    return issue_number, title


# Performs the automatic weekly newsletter title helper step.
def automatic_weekly_newsletter_title(today=None):
    today = today or datetime.datetime.now()
    month_names = [
        "يناير",
        "فبراير",
        "مارس",
        "أبريل",
        "مايو",
        "يونيو",
        "يوليو",
        "أغسطس",
        "سبتمبر",
        "أكتوبر",
        "نوفمبر",
        "ديسمبر",
    ]
    week_names = ["الأول", "الثاني", "الثالث", "الرابع"]
    day = int(today.day)
    if day <= 7:
        week_index = 0
    elif day <= 15:
        week_index = 1
    elif day <= 23:
        week_index = 2
    else:
        week_index = 3
    return f"نشرة الذكاء الاصطناعي الأسبوع {week_names[week_index]} من {month_names[today.month - 1]}"


# Reads read json body from handler from the current store or request context.
def read_json_body_from_handler(handler):
    try:
        length = int(handler.headers.get("Content-Length", 0) or 0)
    except Exception:
        length = 0
    if length <= 0:
        return {}
    raw = handler.rfile.read(length)
    if not raw:
        return {}
    try:
        return json.loads(raw.decode("utf-8"))
    except Exception:
        return {}


# Performs the decode pdf base64 helper step.
def decode_pdf_base64(value):
    text = str(value or "").strip()
    if "," in text and text.lower().startswith("data:"):
        text = text.split(",", 1)[1]
    if not text:
        return b""
    return base64.b64decode(text, validate=False)


# Reads read multipart upload from the current store or request context.
def read_multipart_upload(handler, field_name="pdf", max_bytes=25 * 1024 * 1024):
    length = int(handler.headers.get("Content-Length", 0) or 0)
    if length <= 0:
        return None, "", "empty upload"
    if length > max_bytes:
        handler.rfile.read(length)
        return None, "", "file too large"
    content_type = handler.headers.get("Content-Type", "")
    if "multipart/form-data" not in content_type:
        handler.rfile.read(length)
        return None, "", "expected multipart/form-data"
    body = handler.rfile.read(length)
    header = (
        f"Content-Type: {content_type}\r\n"
        "MIME-Version: 1.0\r\n\r\n"
    ).encode("utf-8", errors="ignore")
    message = BytesParser(policy=email_default_policy).parsebytes(header + body)
    if not message.is_multipart():
        return None, "", "invalid multipart upload"
    fallback = None
    for part in message.iter_parts():
        name = part.get_param("name", header="content-disposition")
        filename = part.get_filename() or ""
        payload = part.get_payload(decode=True) or b""
        if not payload:
            continue
        if name == field_name:
            return payload, filename, ""
        if filename.lower().endswith(".pdf") and fallback is None:
            fallback = (payload, filename)
    if fallback:
        return fallback[0], fallback[1], ""
    return None, "", "no pdf file found"


# Performs the extract pdf text with pypdf helper step.
def extract_pdf_text_with_pypdf(pdf_bytes):
    try:
        from pypdf import PdfReader
    except Exception as exc:
        raise RuntimeError("pypdf is not installed. Rebuild Docker after updating requirements.txt.") from exc
    reader = PdfReader(io.BytesIO(pdf_bytes))
    pages = []
    for page in reader.pages:
        try:
            pages.append(page.extract_text() or "")
        except Exception:
            pages.append("")
    return "\n".join(page for page in pages if page).strip()


# Performs the extract pdf text with pymupdf helper step.
def extract_pdf_text_with_pymupdf(pdf_bytes):
    try:
        import fitz
    except Exception:
        return ""
    pages = []
    with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
        for page in doc:
            try:
                blocks = page.get_text("blocks") or []
                blocks = sorted(blocks, key=lambda block: (round(block[1], 1), round(block[0], 1)))
                text = "\n".join(clean_pdf_line(block[4]) for block in blocks if len(block) > 4 and block[4])
                pages.append(text or page.get_text("text") or "")
            except Exception:
                pages.append("")
    return "\n".join(page for page in pages if page).strip()


# Performs the extract pdf links helper step.
def extract_pdf_links(pdf_bytes):
    links = []
    try:
        import fitz
    except Exception:
        return links
    try:
        with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
            for page_index, page in enumerate(doc):
                for link in page.get_links() or []:
                    uri = str(link.get("uri") or "").strip()
                    if not uri:
                        continue
                    rect = link.get("from")
                    links.append({
                        "url": uri,
                        "page": page_index,
                        "x": float(getattr(rect, "x0", 0) or 0),
                        "y": float(getattr(rect, "y0", 0) or 0),
                    })
    except Exception:
        return links
    links.sort(key=lambda item: (item["page"], item["y"], item["x"]))
    deduped = []
    seen = set()
    for item in links:
        key = item["url"].rstrip("/")
        if key in seen:
            continue
        seen.add(key)
        deduped.append(item)
    return deduped


# Performs the extract pdf text helper step.
def extract_pdf_text(pdf_bytes):
    candidates = []
    for engine, extractor in (
        ("pypdf", extract_pdf_text_with_pypdf),
        ("pymupdf", extract_pdf_text_with_pymupdf),
    ):
        try:
            text = extractor(pdf_bytes)
        except Exception as exc:
            candidates.append((engine, "", str(exc)))
            continue
        candidates.append((engine, text or "", ""))
    engine, text, _error = max(candidates, key=lambda item: len(item[1]), default=("", "", ""))
    extract_pdf_text.last_report = {
        "engine": engine,
        "chars": len(text),
        "attempts": [
            {"engine": name, "chars": len(value or ""), "error": error}
            for name, value, error in candidates
        ],
    }
    return text.strip()


ARABIC_FRAGMENT_RE = re.compile(r"[\u0600-\u06FF]+")


# Performs the repair fragmented arabic text helper step.
def repair_fragmented_arabic_text(text):
    """Repair common PDF extraction artifacts where Arabic words become letter chunks."""
    value = str(text or "")
    if not value:
        return ""

    # Performs the repair sequence helper step.
    def repair_sequence(match):
        sequence = match.group(0)
        tokens = sequence.split()
        if len(tokens) < 2:
            return sequence
        shortish = sum(1 for token in tokens if len(token) <= 3)
        if shortish < max(2, len(tokens) - 1):
            return sequence
        return "".join(tokens)

    previous = None
    while previous != value:
        previous = value
        value = re.sub(
            r"(?<![\u0600-\u06FF])(?:[\u0600-\u06FF]{1,3}\s+){1,8}[\u0600-\u06FF]{1,3}(?![\u0600-\u06FF])",
            repair_sequence,
            value,
        )
    value = re.sub(r"\s+([،؛؟.!:])", r"\1", value)
    value = re.sub(r"([\(])\s+", r"\1", value)
    value = re.sub(r"\s+([\)])", r"\1", value)
    return value


# Prepares clean pdf line so downstream stages receive consistent data.
def clean_pdf_line(value):
    text = unicodedata.normalize("NFKC", str(value or ""))
    text = re.sub(r"\s+", " ", text).strip()
    return repair_fragmented_arabic_text(text.strip("•*-–—| "))


# Performs the pdf domain label helper step.
def pdf_domain_label(url):
    domain = urllib.parse.urlparse(url).netloc.lower().replace("www.", "")
    if not domain:
        return "Imported PDF"
    root = domain.split(".")[0]
    return root.replace("-", " ").title()


# Performs the pdf logo candidates helper step.
def pdf_logo_candidates(url):
    domain = urllib.parse.urlparse(url).netloc.lower().replace("www.", "")
    if not domain:
        return ["image/brand-mark.svg"]
    return [
        f"https://logo.clearbit.com/{domain}",
        f"https://icons.duckduckgo.com/ip3/{domain}.ico",
        f"https://www.google.com/s2/favicons?sz=128&domain={domain}",
    ]


# Prepares clean web meta text so downstream stages receive consistent data.
def clean_web_meta_text(value):
    text = html.unescape(str(value or ""))
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:900]


# Performs the html attr value helper step.
def html_attr_value(attrs, name):
    pattern = rf"""\b{name}\s*=\s*(['"])(.*?)\1"""
    match = re.search(pattern, attrs or "", flags=re.IGNORECASE | re.DOTALL)
    return clean_web_meta_text(match.group(2)) if match else ""


# Fetches fetch url metadata from the configured external source.
def fetch_url_metadata(url):
    raw = str(url or "").strip()
    if not raw.startswith(("http://", "https://")):
        return {"url": raw, "title": "", "description": "", "error": "invalid_url"}
    try:
        request = urllib.request.Request(
            raw,
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; AINewsletterBot/1.0)",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            },
        )
        with urllib.request.urlopen(request, timeout=7) as response:
            content_type = response.headers.get("Content-Type", "")
            charset_match = re.search(r"charset=([\w.-]+)", content_type, flags=re.IGNORECASE)
            charset = charset_match.group(1) if charset_match else "utf-8"
            raw_html = response.read(450_000)
        document = raw_html.decode(charset, errors="ignore")
    except Exception as exc:
        return {"url": raw, "title": "", "description": "", "error": str(exc)[:160]}

    title = ""
    description = ""
    title_match = re.search(r"<title[^>]*>(.*?)</title>", document, flags=re.IGNORECASE | re.DOTALL)
    if title_match:
        title = clean_web_meta_text(title_match.group(1))
    for meta_match in re.finditer(r"<meta\b([^>]+)>", document, flags=re.IGNORECASE | re.DOTALL):
        attrs = meta_match.group(1)
        key = (html_attr_value(attrs, "property") or html_attr_value(attrs, "name")).lower()
        content = html_attr_value(attrs, "content")
        if not content:
            continue
        if key in {"og:title", "twitter:title"}:
            title = content
        elif key in {"description", "og:description", "twitter:description"} and not description:
            description = content
    title = re.sub(r"\s+[\-|–—]\s+[^-|–—]{2,50}$", "", title).strip()
    return {"url": raw, "title": title[:150], "description": description[:700], "error": ""}


# Performs the pdf text needs url metadata helper step.
def pdf_text_needs_url_metadata(value):
    text = str(value or "").strip()
    if not text:
        return True
    if "محتوى مستورد" in text:
        return True
    if len(text) > 115:
        return True
    if re.search(r"[\uFB50-\uFDFF\uFE70-\uFEFF]", text):
        return True
    if re.search(r"[A-Za-z]\) [\u0600-\u06FF]|[\u0600-\u06FF][A-Za-z]{3,}", text):
        return True
    return False


# Performs the title from pdf url helper step.
def title_from_pdf_url(url):
    parsed = urllib.parse.urlparse(str(url or ""))
    domain = parsed.netloc.lower().replace("www.", "")
    path = urllib.parse.unquote(parsed.path or "")
    slug = path.strip("/").split("/")[-1] or domain
    slug = re.sub(r"\.(html?|php|aspx?)$", "", slug, flags=re.IGNORECASE)
    slug = re.sub(r"^\d+[-_]*", "", slug)
    slug = re.sub(r"[-_]+", " ", slug)
    slug = re.sub(r"\b(?:en|ar|articles|article|update|updates|news|learn|course)\b", " ", slug, flags=re.IGNORECASE)
    slug = re.sub(r"\s+", " ", slug).strip()
    if not slug or len(slug) < 8:
        return f"محتوى مستورد من {pdf_domain_label(url)}"
    return slug[:130]


# Performs the pdf card from url helper step.
def pdf_card_from_url(url, index, filename="", content_type="news"):
    source = pdf_domain_label(url)
    title = title_from_pdf_url(url)
    item_id = hashlib.sha1(f"{filename}|{content_type}|{index}|{title}|{url}".encode("utf-8", errors="ignore")).hexdigest()[:24]
    logos = pdf_logo_candidates(url)
    base = {
        "id": item_id,
        "title": title,
        "text": "محتوى مستورد من رابط داخل PDF. يمكن تعديل العنوان والوصف والرابط من صفحة التحرير.",
        "url": url,
        "source": source,
        "published": "",
        "story_key": item_id,
        "type": content_type,
        "status": "display" if content_type == "news" and index <= DISPLAY_COUNTS.get("items", 6) else "",
        "position": index,
        "logo": logos[0],
        "logo_size": 30,
        "logo_x": 0,
        "logo_y": 0,
        "logo_candidates": logos,
        "logo_manual_override": False,
        "logo_override_url": "",
    }
    if content_type == "course":
        base.update({
            "provider": source,
            "platform": source,
            "level": "",
            "certificate": "",
        })
    else:
        base.update({
            "company": source,
            "tool_name": source,
            "field_primary": "imported_pdf",
            "use_case_bucket": "imported_pdf",
            "topic_family": "imported_pdf",
            "sector": "مستورد من PDF",
            "is_highlight": index == 1,
            "highlight_reason": "مستورد من ملف PDF",
            "simple_gpt_selected": False,
            "story_signature": item_id,
            "story_owner": source.lower().replace(" ", "-"),
        })
    return base


# Performs the split pdf link cards helper step.
def split_pdf_link_cards(pdf_links, filename=""):
    news_cards = []
    course_cards = []
    course_domains = ("edx.org", "udacity.com", "coursera.org", "linkedin.com", "deeplearning.ai", "kaggle.com")
    for link in pdf_links or []:
        url = str(link.get("url") or "").strip()
        if not url:
            continue
        domain = urllib.parse.urlparse(url).netloc.lower()
        if any(course_domain in domain for course_domain in course_domains):
            course_cards.append(pdf_card_from_url(url, len(course_cards) + 1, filename, content_type="course"))
        else:
            news_cards.append(pdf_card_from_url(url, len(news_cards) + 1, filename, content_type="news"))
    return news_cards, course_cards


# Performs the extract pdf layout entries helper step.
def extract_pdf_layout_entries(pdf_bytes, pdf_links, filename=""):
    """Rebuild fixed-layout newsletter cards from text block coordinates and link anchors."""
    entries = []
    if not pdf_links:
        return entries
    try:
        import fitz
    except Exception:
        return entries
    try:
        with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
            page_blocks = {}
            page_sizes = {}
            for page_index, page in enumerate(doc):
                page_sizes[page_index] = (float(page.rect.width), float(page.rect.height))
                blocks = []
                for block in page.get_text("blocks") or []:
                    if len(block) <= 4:
                        continue
                    text = clean_pdf_line(block[4])
                    if not text:
                        continue
                    blocks.append({
                        "x0": float(block[0]),
                        "y0": float(block[1]),
                        "x1": float(block[2]),
                        "y1": float(block[3]),
                        "text": text,
                    })
                page_blocks[page_index] = blocks
    except Exception:
        return entries

    course_domains = ("edx.org", "udacity.com", "coursera.org", "linkedin.com", "deeplearning.ai", "kaggle.com")
    for link in sorted(pdf_links or [], key=lambda item: (item.get("page", 0), item.get("y", 0), item.get("x", 0))):
        url = str(link.get("url") or "").strip()
        if not url:
            continue
        page_index = int(link.get("page") or 0)
        page_width, page_height = page_sizes.get(page_index, (794.0, 1123.0))
        x = float(link.get("x") or 0)
        y = float(link.get("y") or 0)
        is_left = x < (page_width / 2)
        is_course = any(domain in urllib.parse.urlparse(url).netloc.lower() for domain in course_domains) or y > page_height * 0.72
        if is_course:
            x0, x1 = 0, page_width
            y0, y1 = max(0, y - 135), min(page_height, y + 40)
        else:
            margin = 22
            gutter = 14
            mid = page_width / 2
            x0 = margin if is_left else mid + gutter
            x1 = mid - gutter if is_left else page_width - margin
            y0, y1 = max(0, y - 210), min(page_height, y + 35)
        selected = []
        for block in page_blocks.get(page_index, []):
            cx = (block["x0"] + block["x1"]) / 2
            cy = (block["y0"] + block["y1"]) / 2
            if x0 <= cx <= x1 and y0 <= cy <= y1:
                text = block["text"]
                if not text or "المصدر" in text[:20] or text.lower().strip() in {"source"}:
                    continue
                selected.append(block)
        selected.sort(key=lambda block: (block["y0"], block["x0"]))
        lines = [block["text"] for block in selected]
        entries.append({
            "url": url,
            "content_type": "course" if is_course else "news",
            "lines": lines,
            "page": page_index,
            "x": x,
            "y": y,
        })
    return entries


# Performs the cards from layout entries helper step.
def cards_from_layout_entries(entries, filename=""):
    news_cards = []
    course_cards = []
    for entry in entries or []:
        url = entry.get("url") or "#"
        lines = [clean_pdf_line(line) for line in entry.get("lines") or [] if clean_pdf_line(line)]
        content_type = entry.get("content_type") or "news"
        index = (len(course_cards) + 1) if content_type == "course" else (len(news_cards) + 1)
        card = pdf_card_from_url(url, index, filename, content_type=content_type)
        if lines:
            title = lines[0]
            body = " ".join(lines[1:]).strip()
            if len(title) > 150 and not body:
                parts = re.split(r"(?<=[.!؟])\s+", title, maxsplit=1)
                title = parts[0]
                body = parts[1] if len(parts) > 1 else ""
            card["title"] = title[:150]
            if body:
                card["text"] = body[:900]
        if content_type == "course":
            course_cards.append(card)
        else:
            news_cards.append(card)
    return news_cards, course_cards


# Performs the split pdf article blocks helper step.
def split_pdf_article_blocks(lines):
    url_pattern = re.compile(r"https?://[^\s)>\]}\"']+", re.IGNORECASE)
    blocks = []
    current = []
    for line in lines:
        if not line:
            continue
        current.append(line)
        if url_pattern.search(line) or line in {"المصدر", "Source", "SOURCE"}:
            if len(current) >= 2:
                blocks.append(current)
                current = []
    if current:
        blocks.append(current)
    if len(blocks) <= 1 and len(lines) > 8:
        blocks = []
        chunk = []
        for line in lines:
            chunk.append(line)
            if len(chunk) >= 6:
                blocks.append(chunk)
                chunk = []
        if chunk:
            blocks.append(chunk)
    return blocks


# Performs the parse pdf newsletter text helper step.
def parse_pdf_newsletter_text(text, filename="", pdf_links=None):
    url_pattern = re.compile(r"https?://[^\s)>\]}\"']+", re.IGNORECASE)
    annotation_urls = [
        str(item.get("url") or "").strip()
        for item in (pdf_links or [])
        if str(item.get("url") or "").strip()
    ]
    raw_lines = [clean_pdf_line(line) for line in str(text or "").splitlines()]
    skip_markers = (
        "نشرة أخبار",
        "الذكاء الاصطناعي",
        "المرصد الثقافي",
        "الإصدار",
        "آخر حفظ",
    )
    lines = [
        line for line in raw_lines
        if line and not any(marker in line for marker in skip_markers)
    ]
    blocks = split_pdf_article_blocks(lines)
    items = []
    for block in blocks:
        joined = " ".join(block)
        urls = [match.group(0).rstrip(".,،؛)") for match in url_pattern.finditer(joined)]
        url = urls[0] if urls else (annotation_urls[len(items)] if len(items) < len(annotation_urls) else "#")
        clean_block = [url_pattern.sub("", line).strip(" -:：") for line in block]
        clean_block = [
            line for line in clean_block
            if line and line.lower() not in {"source", "المصدر"} and "المصدر" not in line[:12]
        ]
        if not clean_block:
            continue
        title = clean_block[0][:130]
        body_lines = clean_block[1:] if len(clean_block) > 1 else []
        text_body = " ".join(body_lines).strip()
        if len(text_body) < 40 and len(clean_block) >= 2:
            title = clean_block[0][:100]
            text_body = " ".join(clean_block[1:]).strip()
        if not text_body:
            text_body = "محتوى مستورد من ملف PDF. يمكن تعديل النص والرابط من صفحة التحرير."
        source = pdf_domain_label(url)
        item_id = hashlib.sha1(f"{filename}|{len(items)}|{title}|{url}".encode("utf-8", errors="ignore")).hexdigest()[:24]
        logos = pdf_logo_candidates(url)
        item = {
            "id": item_id,
            "title": title,
            "text": text_body[:900],
            "url": url,
            "source": source,
            "published": "",
            "story_key": item_id,
            "type": "news",
            "status": "display" if len(items) < DISPLAY_COUNTS.get("items", 6) else "backup",
            "position": len(items) + 1,
            "logo": logos[0],
            "logo_size": 30,
            "logo_x": 0,
            "logo_y": 0,
            "logo_candidates": logos,
            "logo_manual_override": False,
            "logo_override_url": "",
            "company": source,
            "tool_name": source,
            "field_primary": "imported_pdf",
            "use_case_bucket": "imported_pdf",
            "topic_family": "imported_pdf",
            "sector": "مستورد من PDF",
            "is_highlight": len(items) == 0,
            "highlight_reason": "مستورد من ملف PDF",
            "simple_gpt_selected": False,
            "story_signature": item_id,
            "story_owner": source.lower().replace(" ", "-"),
        }
        items.append(item)
        if len(items) >= 12:
            break
    return items


# Performs the imported pdf news payload helper step.
def imported_pdf_news_payload(text, filename="", pdf_links=None, layout_entries=None):
    settings = load_newsletter_settings()
    template = newsletter_template_from_settings(settings)
    all_items = parse_pdf_newsletter_text(text, filename, pdf_links=pdf_links)
    link_news_items, link_course_items = split_pdf_link_cards(pdf_links or [], filename)
    layout_news_items, layout_course_items = cards_from_layout_entries(layout_entries or [], filename)
    link_count = len(link_news_items) + len(link_course_items)
    layout_count = len(layout_news_items) + len(layout_course_items)
    if layout_count >= max(4, min(6, link_count or layout_count)):
        all_items = layout_news_items
        course_items = layout_course_items
        import_mode = "pdf_layout"
    elif link_count and len(all_items) < max(3, min(6, link_count // 2)):
        all_items = link_news_items
        course_items = link_course_items
        import_mode = "pdf_links_fallback"
    else:
        course_items = []
        import_mode = "pdf_text_parse"
    if not all_items:
        raise ValueError("Could not find newsletter articles in the PDF text.")
    visible_count = DISPLAY_COUNTS.get("items", 6)
    visible = all_items[:visible_count]
    backups = all_items[visible_count:]
    for index, item in enumerate([*visible, *backups], start=1):
        item["position"] = index
        item["status"] = "display" if index <= visible_count else "backup"
    payload = {
        "items": visible,
        "backup_news": backups,
        "movies": [],
        "courses": course_items,
        "template": template,
        "feature_mode": "course",
        "metadata": {
            "source": "pdf_import",
            "pdf_import_mode": import_mode,
            "imported_filename": filename,
            "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "display_count": len(visible),
            "backup_count": len(backups),
            "news_total_count": len(all_items),
            "pdf_link_count": link_count,
            "pdf_layout_count": layout_count,
        },
    }
    enrich_imported_pdf_payload_from_urls(payload)
    return payload


# Performs the enrich imported pdf payload from urls helper step.
def enrich_imported_pdf_payload_from_urls(payload):
    if not isinstance(payload, dict):
        return payload
    cards = []
    for section in ("items", "backup_news", "courses"):
        for item in payload.get(section) or []:
            if isinstance(item, dict) and item.get("url") and item.get("url") != "#":
                cards.append(item)
    if not cards:
        return payload
    url_to_cards = {}
    for card in cards:
        url_to_cards.setdefault(card.get("url"), []).append(card)
    metadata_by_url = {}
    with ThreadPoolExecutor(max_workers=min(6, max(1, len(url_to_cards)))) as executor:
        future_map = {executor.submit(fetch_url_metadata, url): url for url in url_to_cards}
        for future in as_completed(future_map):
            url = future_map[future]
            try:
                metadata_by_url[url] = future.result()
            except Exception as exc:
                metadata_by_url[url] = {"url": url, "title": "", "description": "", "error": str(exc)[:160]}
    enriched = 0
    for url, linked_cards in url_to_cards.items():
        metadata = metadata_by_url.get(url) or {}
        title = clean_web_meta_text(metadata.get("title") or "")
        description = clean_web_meta_text(metadata.get("description") or "")
        for card in linked_cards:
            if title and pdf_text_needs_url_metadata(card.get("title")):
                card["title"] = title
            if description and pdf_text_needs_url_metadata(card.get("text")):
                card["text"] = description
            if title or description:
                card["pdf_import_metadata"] = {
                    "title": title,
                    "description": description,
                    "source": "url_metadata",
                    "error": metadata.get("error") or "",
                }
                enriched += 1
    metadata = payload.get("metadata") if isinstance(payload.get("metadata"), dict) else {}
    metadata["pdf_url_metadata_enriched"] = enriched
    metadata["pdf_url_metadata_attempted"] = len(url_to_cards)
    payload["metadata"] = metadata
    trace(f"PDF import URL metadata enriched={enriched}/{len(url_to_cards)}")
    return payload


# Saves save imported version to the configured output or state store.
def save_imported_version(payload, filename=""):
    content = json.dumps(payload, ensure_ascii=False, indent=2)
    issue_number = safe_int((payload.get("template") or {}).get("issue_number"), 1)
    title = f"نسخة مستوردة من PDF — {Path(filename or 'newsletter.pdf').stem}"
    init_versions_db()
    con = versions_db()
    try:
        # PostgreSQL change: RETURNING id replaces SQLite cursor.lastrowid.
        with con.cursor() as cur:
            cur.execute(
                "INSERT INTO versions (issue_number, title, content) VALUES (%s, %s, %s) RETURNING id",
                (issue_number, title, content),
            )
            new_id = cur.fetchone()[0]
        con.commit()
    finally:
        con.close()
    backup_versions_db()
    return new_id, title


# Saves attach newsletter json to pdf to the configured output or state store.
def attach_newsletter_json_to_pdf(pdf_bytes, newsletter_payload):
    if not isinstance(newsletter_payload, dict) or not newsletter_payload.get("items"):
        return pdf_bytes
    try:
        from pypdf import PdfReader, PdfWriter
    except Exception as exc:
        trace(f"PDF JSON attachment skipped: pypdf unavailable: {exc}")
        return pdf_bytes
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        writer = PdfWriter()
        for page in reader.pages:
            writer.add_page(page)
        try:
            if reader.metadata:
                writer.add_metadata({str(k): str(v) for k, v in dict(reader.metadata).items() if v is not None})
        except Exception:
            pass
        payload = dict(newsletter_payload)
        metadata = payload.get("metadata") if isinstance(payload.get("metadata"), dict) else {}
        metadata.update({
            "embedded_in_pdf": True,
            "embedded_schema": "ainewsletter_version_v1",
            "embedded_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        })
        payload["metadata"] = metadata
        attachment_bytes = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
        writer.add_attachment("ainewsletter-version.json", attachment_bytes)
        output = io.BytesIO()
        writer.write(output)
        trace(f"PDF export embedded JSON attachment bytes={len(attachment_bytes)}")
        return output.getvalue()
    except Exception as exc:
        trace(f"PDF JSON attachment failed: {exc}")
        return pdf_bytes


# Performs the extract embedded newsletter payload helper step.
def extract_embedded_newsletter_payload(pdf_bytes):
    try:
        from pypdf import PdfReader
    except Exception:
        return None
    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        attachments = getattr(reader, "attachments", {}) or {}
    except Exception:
        return None
    candidates = []
    if isinstance(attachments, dict):
        for name, values in attachments.items():
            if not str(name).lower().endswith(".json"):
                continue
            if isinstance(values, (bytes, bytearray)):
                candidates.append((name, bytes(values)))
            else:
                for value in values or []:
                    if isinstance(value, (bytes, bytearray)):
                        candidates.append((name, bytes(value)))
    for name, raw in candidates:
        try:
            payload = json.loads(raw.decode("utf-8"))
        except Exception:
            continue
        if isinstance(payload, dict) and isinstance(payload.get("items"), list):
            trace(f"PDF import found embedded JSON attachment name={name} items={len(payload.get('items') or [])}")
            return payload
    return None


# Saves save pdf import debug to the configured output or state store.
def save_pdf_import_debug(filename, extracted_text, payload, extract_report, pdf_links=None, layout_entries=None):
    try:
        PDF_IMPORT_DEBUG_DIR.mkdir(parents=True, exist_ok=True)
        debug_text_path = PDF_IMPORT_DEBUG_DIR / "pdf_import_last.txt"
        debug_json_path = PDF_IMPORT_DEBUG_DIR / "pdf_import_last.json"
        debug_text_path.write_text(extracted_text or "", encoding="utf-8")
        debug_payload = {
            "filename": filename,
            "extract": extract_report,
            "pdf_links": pdf_links or [],
            "layout_entries": layout_entries or [],
            "articles": len(payload.get("items") or []) + len(payload.get("backup_news") or []) if isinstance(payload, dict) else 0,
            "items": (payload or {}).get("items", []) if isinstance(payload, dict) else [],
            "backup_news": (payload or {}).get("backup_news", []) if isinstance(payload, dict) else [],
        }
        debug_json_path.write_text(json.dumps(debug_payload, ensure_ascii=False, indent=2), encoding="utf-8")
        return {"text": str(debug_text_path), "json": str(debug_json_path)}
    except Exception as exc:
        trace(f"PDF import debug write failed: {exc}")
        return {}


# Handles handle versions get for the HTTP API layer.
def handle_versions_get(handler, path):
    if path == f"{API_BASE}/versions":
        init_versions_db()
        user = handler.current_user() if hasattr(handler, "current_user") else None
        is_admin = bool(user and user.get("is_admin"))
        con = versions_db()
        try:
            # PDF BYTEA change: report PDF size from PostgreSQL binary data while
            # leaving JSON content-size behavior unchanged.
            with con.cursor() as cur:
                cur.execute(
                    """
                    SELECT id, issue_number, title, created_at,
                           CASE
                               WHEN COALESCE(kind, 'json') = 'pdf' THEN COALESCE(octet_length(pdf_data), 0)
                               ELSE length(content)
                           END,
                           kind, pdf_path, original_filename, COALESCE(hidden_from_users, FALSE)
                    FROM versions
                    WHERE (%s OR NOT COALESCE(hidden_from_users, FALSE))
                    ORDER BY created_at DESC, id DESC
                    """,
                    (is_admin,),
                )
                rows = cur.fetchall()
        finally:
            con.close()
        items = []
        for row in rows:
            kind = (row[5] or "json").strip() or "json"
            size = row[4] or 0
            items.append({
                "id": row[0],
                "issue_number": row[1],
                "title": row[2],
                "created_at": serialize_db_datetime(row[3]),
                "content_size": size,
                "kind": kind,
                "original_filename": row[7] or "",
                "hidden_from_users": bool(row[8]),
            })
        handler.send_json([
            item for item in items
        ])
        return True

    pdf_version_id = parse_version_id(path, "/pdf")
    if pdf_version_id is not None:
        init_versions_db()
        con = versions_db()
        try:
            # PDF BYTEA change: load binary data directly from PostgreSQL instead
            # of resolving and reading the deprecated local pdf_path.
            with con.cursor() as cur:
                cur.execute(
                    "SELECT title, kind, pdf_data, original_filename, COALESCE(hidden_from_users, FALSE) FROM versions WHERE id = %s",
                    (pdf_version_id,),
                )
                row = cur.fetchone()
        finally:
            con.close()
        if not row:
            handler.send_json({"error": "not found"}, 404)
            return True
        user = handler.current_user() if hasattr(handler, "current_user") else None
        if row[4] and not (user and user.get("is_admin")):
            handler.send_json({"error": "not found"}, 404)
            return True
        if (row[1] or "json") != "pdf":
            handler.send_json({"error": "version is not a PDF"}, 400)
            return True
        if row[2] is None:
            handler.send_json({"error": "PDF data not found"}, 404)
            return True
        # PDF BYTEA change: psycopg2 returns BYTEA as memoryview; convert it to
        # bytes before streaming with the unchanged application/pdf response.
        payload = bytes(row[2])
        display_name = str(row[0] or row[3] or f"version_{pdf_version_id}.pdf").strip()
        display_name = re.sub(r"[\r\n\\/]+", "_", display_name).strip("._ ") or f"version_{pdf_version_id}"
        if not display_name.lower().endswith(".pdf"):
            display_name = f"{display_name}.pdf"
        quoted_name = urllib.parse.quote(display_name)
        handler.send_response(200)
        handler.send_header("Content-Type", "application/pdf")
        handler.send_header("Content-Disposition", f"inline; filename*=UTF-8''{quoted_name}")
        handler.send_header("Content-Length", str(len(payload)))
        handler.end_headers()
        handler.wfile.write(payload)
        return True

    export_version_id = parse_version_id(path, "/export")
    if export_version_id is not None:
        init_versions_db()
        con = versions_db()
        try:
            # PostgreSQL change: retrieve export content through a psycopg2 cursor.
            with con.cursor() as cur:
                cur.execute("SELECT content, COALESCE(hidden_from_users, FALSE) FROM versions WHERE id = %s", (export_version_id,))
                row = cur.fetchone()
        finally:
            con.close()
        if not row:
            handler.send_json({"error": "not found"}, 404)
            return True
        user = handler.current_user() if hasattr(handler, "current_user") else None
        if row[1] and not (user and user.get("is_admin")):
            handler.send_json({"error": "not found"}, 404)
            return True
        payload = str(row[0] or "{}").encode("utf-8")
        handler.send_response(200)
        handler.send_header("Content-Type", "application/json")
        handler.send_header("Content-Disposition", f'attachment; filename="version_{export_version_id}.json"')
        handler.send_header("Content-Length", str(len(payload)))
        handler.end_headers()
        handler.wfile.write(payload)
        return True

    version_id = parse_version_id(path)
    if version_id is not None:
        init_versions_db()
        con = versions_db()
        try:
            # PostgreSQL change: retrieve one version with a parameterized cursor.
            with con.cursor() as cur:
                cur.execute(
                    "SELECT id, issue_number, title, created_at, content, kind, COALESCE(hidden_from_users, FALSE) FROM versions WHERE id = %s",
                    (version_id,),
                )
                row = cur.fetchone()
        finally:
            con.close()
        if not row:
            handler.send_json({"error": "not found"}, 404)
            return True
        user = handler.current_user() if hasattr(handler, "current_user") else None
        if row[6] and not (user and user.get("is_admin")):
            handler.send_json({"error": "not found"}, 404)
            return True
        try:
            content = json.loads(row[4] or "{}")
        except Exception:
            content = row[4] or "{}"
        handler.send_json({
            "id": row[0],
            "issue_number": row[1],
            "title": row[2],
            "created_at": serialize_db_datetime(row[3]),
            "content": content,
            "kind": row[5] or "json",
        })
        return True

    return False


# Handles handle versions post for the HTTP API layer.
def handle_versions_post(handler, path):
    convert_pdf_version_id = parse_version_id(path, "/pdf")
    if convert_pdf_version_id is not None:
        data = read_json_body_from_handler(handler)
        try:
            pdf_bytes = decode_pdf_base64(data.get("pdf_base64") or data.get("pdf"))
        except Exception:
            handler.send_json({"success": False, "error": "invalid pdf payload"}, 400)
            return True
        if not pdf_bytes:
            handler.send_json({"success": False, "error": "empty PDF payload"}, 400)
            return True
        filename = str(data.get("filename") or f"version_{convert_pdf_version_id}.pdf").strip()
        if not filename.lower().endswith(".pdf"):
            filename = f"{filename}.pdf"
        init_versions_db()
        con = versions_db()
        try:
            with con.cursor() as cur:
                cur.execute("SELECT id, title, kind FROM versions WHERE id = %s", (convert_pdf_version_id,))
                row = cur.fetchone()
                if not row:
                    handler.send_json({"success": False, "error": "not found"}, 404)
                    return True
                cur.execute(
                    """
                    UPDATE versions
                    SET kind = 'pdf', pdf_data = %s, pdf_path = NULL, original_filename = %s
                    WHERE id = %s
                    """,
                    (psycopg2.Binary(pdf_bytes), filename, convert_pdf_version_id),
                )
            con.commit()
        except Exception:
            con.rollback()
            raise
        finally:
            con.close()
        backup_versions_db()
        handler.send_json({
            "success": True,
            "id": convert_pdf_version_id,
            "kind": "pdf",
            "size": len(pdf_bytes),
        })
        return True

    if path == f"{API_BASE}/versions/import-pdf":
        pdf_bytes, filename, upload_error = read_multipart_upload(handler, field_name="pdf")
        if upload_error:
            handler.send_json({"success": False, "error": upload_error}, 400)
            return True
        trace(f"PDF import upload filename={filename or '-'} bytes={len(pdf_bytes or b'')}")
        if not pdf_bytes:
            handler.send_json({"success": False, "error": "empty PDF upload"}, 400)
            return True
        try:
            title = title_from_pdf_filename(filename)
            init_versions_db()
            con = versions_db()
            try:
                # PDF BYTEA change: insert PDF metadata first to obtain the ID
                # used by the binary update in the same PostgreSQL transaction.
                with con.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO versions (issue_number, title, content, kind, original_filename)
                        VALUES (%s, %s, %s, %s, %s)
                        RETURNING id
                        """,
                        (None, title, "", "pdf", filename or "imported.pdf"),
                    )
                    new_id = cur.fetchone()[0]
                # PDF BYTEA change: store the uploaded bytes in the same database
                # transaction; no local file is created and pdf_path stays NULL.
                save_pdf_version_file(new_id, pdf_bytes, filename, connection=con)
                con.commit()
            finally:
                con.close()
            backup_versions_db()
            trace(f"PDF import saved PostgreSQL bytes version_id={new_id} title={title!r} bytes={len(pdf_bytes)}")
        except Exception as exc:
            trace(f"PDF import failed: {exc}")
            handler.send_json({"success": False, "error": str(exc)}, 500)
            return True
        handler.send_json({
            "success": True,
            "id": new_id,
            "title": title,
            "kind": "pdf",
            "size": len(pdf_bytes),
        })
        return True

    if path == f"{API_BASE}/versions":
        init_versions_db()
        content = load_current_news_json_text()
        if not content.strip():
            handler.send_json({"error": "no content"}, 400)
            return True
        issue_number, title = version_title_from_news(content)
        title = automatic_weekly_newsletter_title()
        con = versions_db()
        try:
            # PostgreSQL change: save the current newsletter and return its new
            # identity while preserving the existing POST response.
            with con.cursor() as cur:
                cur.execute(
                    "INSERT INTO versions (issue_number, title, content) VALUES (%s, %s, %s) RETURNING id",
                    (issue_number, title, content),
                )
                new_id = cur.fetchone()[0]
            con.commit()
        finally:
            con.close()
        backup_versions_db()
        publish_current_store()
        handler.send_json({"id": new_id})
        return True

    restore_version_id = parse_version_id(path, "/restore")
    if restore_version_id is not None:
        init_versions_db()
        con = versions_db()
        try:
            # PostgreSQL change: load restore content through a safe parameterized query.
            with con.cursor() as cur:
                cur.execute("SELECT content, kind FROM versions WHERE id = %s", (restore_version_id,))
                row = cur.fetchone()
        finally:
            con.close()
        if not row:
            handler.send_json({"error": "not found"}, 404)
            return True
        if (row[1] or "json") == "pdf":
            handler.send_json({"error": "PDF versions open as files and cannot be restored for editing"}, 400)
            return True
        try:
            json.loads(row[0] or "{}")
        except Exception:
            handler.send_json({"error": "Stored version content is not valid JSON"}, 500)
            return True
        NEWS_JSON_FILE.write_text(row[0] or "{}", encoding="utf-8")
        handler.send_json({"ok": True})
        return True

    return False


# Handles handle versions put for the HTTP API layer.
def handle_versions_put(handler, path, data):
    version_id = parse_version_id(path)
    if version_id is None:
        return False
    title = str(data.get("title") or "").strip()
    created_at = str(data.get("created_at") or "").strip()
    hidden_present = "hidden_from_users" in data
    hidden_from_users = bool(data.get("hidden_from_users")) if hidden_present else None
    save_current = bool(data.get("save_current") or data.get("update_content"))
    content = load_current_news_json_text() if save_current else ""
    issue_number = None
    if save_current:
        if not content.strip():
            handler.send_json({"error": "no content"}, 400)
            return True
        issue_number, derived_title = version_title_from_news(content)
        derived_title = automatic_weekly_newsletter_title()
        title = title or derived_title
    parsed_created_at = None
    if created_at:
        try:
            date_text = created_at.replace("Z", "+00:00")
            parsed = datetime.datetime.fromisoformat(date_text)
            if isinstance(parsed, datetime.datetime):
                parsed_created_at = parsed.replace(tzinfo=None)
        except Exception:
            try:
                parsed_created_at = datetime.datetime.combine(
                    datetime.date.fromisoformat(created_at),
                    datetime.time.min,
                )
            except Exception:
                handler.send_json({"error": "invalid created_at"}, 400)
                return True
    if not title and not save_current and not parsed_created_at and not hidden_present:
        handler.send_json({"error": "title, created_at, hidden_from_users, or save_current is required"}, 400)
        return True
    init_versions_db()
    con = versions_db()
    try:
        # PostgreSQL change: keep PDF overwrite protection using a psycopg2 cursor.
        with con.cursor() as cur:
            cur.execute("SELECT kind FROM versions WHERE id = %s", (version_id,))
            existing = cur.fetchone()
        if save_current and existing and (existing[0] or "json") == "pdf":
            handler.send_json({"error": "PDF versions cannot be edited or overwritten"}, 400)
            return True
        # PostgreSQL change: update content or title with %s parameters while
        # retaining the same row-count behavior expected by the API.
        with con.cursor() as cur:
            if save_current:
                cur.execute(
                    """
                    UPDATE versions
                    SET issue_number = %s, title = %s, content = %s
                    WHERE id = %s
                    """,
                    (issue_number, title, content, version_id),
                )
            else:
                updates = []
                values = []
                if title:
                    updates.append("title = %s")
                    values.append(title)
                if parsed_created_at:
                    updates.append("created_at = %s")
                    values.append(parsed_created_at)
                if hidden_present:
                    updates.append("hidden_from_users = %s")
                    values.append(hidden_from_users)
                cur.execute(
                    f"UPDATE versions SET {', '.join(updates)} WHERE id = %s",
                    (*values, version_id),
                )
            updated = cur.rowcount
        con.commit()
    finally:
        con.close()
    if not updated:
        handler.send_json({"error": "not found"}, 404)
        return True
    if save_current:
        backup_versions_db()
        publish_current_store()
    response = {"ok": True, "id": version_id, "updated_content": save_current}
    if hidden_present:
        response["hidden_from_users"] = hidden_from_users
    handler.send_json(response)
    return True


# Handles handle versions delete for the HTTP API layer.
def handle_versions_delete(handler, path):
    version_id = parse_version_id(path)
    if version_id is None:
        return False
    init_versions_db()
    con = versions_db()
    try:
        # PDF BYTEA change: deleting a version now removes its PostgreSQL row and
        # embedded bytes together. Legacy files are intentionally left untouched.
        with con.cursor() as cur:
            cur.execute("DELETE FROM versions WHERE id = %s", (version_id,))
            deleted = cur.rowcount
        con.commit()
    finally:
        con.close()
    if not deleted:
        handler.send_json({"error": "not found"}, 404)
        return True
    backup_versions_db()
    handler.send_json({"ok": True})
    return True

